name: Android CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip wget
          
          # Download and install command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Accept SDK licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install required SDK packages
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Check if Gradle Wrapper Exists
        run: ls -la gradlew || echo "Gradle Wrapper NOT found!"

      - name: Fix Gradlew Line Endings
        run: sed -i -e 's/\r$//' gradlew

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Clean and Sync Dependencies
        run: ./gradlew clean build --refresh-dependencies --no-daemon
        
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      # 1️⃣2️⃣ **Upload Release APK (Optional)**
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: app/build/outputs/apk/release/app-release.apk
